### ISSUE TITLE
flexible Image with boolean/number/text

### ISSUE THREAD

**Issue by EdgarM73** [EdgarM73/ioBroker.vis-material-advanced#13]
**Describe the solution you'd like**
the possibility to have a flexible widget which shows only boolean or Text.

Name could be ListFlexible and Icon ...

**Comment by EdgarM73** [comment]
also some kind of check could be done and the color could change depending on that.

**Comment by duczz** [comment]
card icon does not change, standard icon is fix

**Comment by EdgarM73** [comment]
I have tested it right now, and the icon changes from checked to unchecked.

Is it a boolean DP you are using? Or a test/number one?

**Comment by duczz** [comment]
Yes its a boolean DP

**Comment by duczz** [comment]
Yes its a boolean DP

![image](https://user-images.githubusercontent.com/25475385/91667135-8611d900-eb02-11ea-90e4-7832b7768742.png)

**Comment by EdgarM73** [comment]
all implemented
