### ISSUE TITLE
Einige Widgets werden nicht angezeigt

### ISSUE THREAD

**Issue by Fruitsmart** [EdgarM73/ioBroker.vis-material-advanced#15]
Hallo bei mir werden sowohl im Editor als auch im vis nur folgende Widgets angezeigt.

Temperature
Door
Window
Light
Dimmer

Was kann das sein? Vis Upload habe ich schon gemacht.

Gruß Michel

**Comment by EdgarM73** [comment]
Geht es inzwischen, hast nicht auf meinen Kommentar reagiert :)

**Comment by Fruitsmart** [comment]
Hey sorry. Ich hatte den alten Adapter drauf. Ist aber nur deiner installiert. Es wird mir nicht mehr angezeigt.

**Comment by EdgarM73** [comment]
Kein Thema :)

**Comment by Fruitsmart** [comment]
Achso die Widgets werden trotzdem nicht angezeigt.

**Comment by Fruitsmart** [comment]
> Kein Thema :)



> Kein Thema :)

Achso die Widgets werden trotzdem nicht angezeigt
